### ISSUE TITLE
Can't install zold

### ISSUE THREAD

**Issue by silverbonegg** [yegor256/zold#101]
Below is transcript from my putty session.  Any ideas? Thanks!

root@ubuntu-c-1vcpu-2gb-nyc3-01:~# gem install zold
Building native extensions.  This could take a while...
ERROR:  Error installing zold:
        ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/gherkin-2.12.2/ext/gherkin_lexer_ar
/usr/bin/ruby2.3 -r ./siteconf20180530-6894-1nhgbz.rb extconf.rb
checking for main() in -lc... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@silverbonegg[/z](https://www.0crat.com/u/silverbonegg) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C91QJT4CF) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!
