### ISSUE TITLE
ZLD capacity 

### ISSUE THREAD

**Issue by amihaiemil** [yegor256/zold#111]
The whitepaper says the following:

```
Capacity. One currency unit is called ZLD. One ZLD by convention equals
to 232 zents (4,294,967,296). All amounts are stored as signed 64-bit integers.
Thus, the technical capacity of the currency is 2,147,483,648 ZLD (two
billion).
```

How did you come up with ``2,147,483,684 ZLD``? The paragraph doesn't say *how many* 64-bit integers? Or am I missing something?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C91QJT4CF) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@amihaiemil 2^63 / 2^32 = 2^31, which is 2 billion

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
