### ISSUE TITLE
node auto-restart on version update

### ISSUE THREAD

**Issue by yegor256** [yegor256/zold#64]
Would be great if a node would restart itself (somehow) when a new version is published on Rubygems. Maybe, the node has to restart when it sees that any remote node version is higher that its own.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@fa07475b-299d-4e6f-abbf-66307a6d6029, thread: pool-648-thread-1
com.zerocracy.pm.Claims[112] java.lang.IllegalStateException: Duplicate claims are not allowed in [C91QJT4CF](https://www.0crat.com/p/C91QJT4CF), can't add this XML to 3 existing ones:
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1471059764">
   <created>2018-05-27T10:29:20.237Z</created>
   <type>Add job to WBS</type>
   <token>github;zerocracy/zold;64</token>
   <params>
      <param name="job">gh:zerocracy/zold#64</param>
      <param name="role">DEV</param>
      <param name="reason">GitHub issue was assigned to 0crat</param>
   </params>
</claim>

```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): Issue: zerocracy/zold#64, Action: `assigned`

**Comment by 0crat** [comment]
Job [#64](https://github.com/zerocracy/zold/issues/64) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@fa07475b-299d-4e6f-abbf-66307a6d6029, thread: pool-647-thread-1
com.zerocracy.pm.Claims[112] java.lang.IllegalStateException: Duplicate claims are not allowed in [C91QJT4CF](https://www.0crat.com/p/C91QJT4CF), can't add this XML to 3 existing ones:
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1471059769">
   <created>2018-05-27T10:29:26.656Z</created>
   <type>Add job to WBS</type>
   <token>github;zerocracy/zold;64</token>
   <params>
      <param name="job">gh:zerocracy/zold#64</param>
      <param name="role">DEV</param>
      <param name="reason">GitHub issue was assigned to 0crat</param>
   </params>
</claim>

```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): Issue: zerocracy/zold#64, Action: `assigned`

**Comment by 0crat** [comment]
Job [#64](https://github.com/zerocracy/zold/issues/64) is already in scope

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#64](https://github.com/zerocracy/zold/issues/64); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
The job [#64](https://github.com/yegor256/zold/issues/64) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C91QJT4CF/1481329461); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)com.zerocracy.Par@60035a18

**Comment by 0crat** [comment]
Job `gh:yegor256/zold#64` already assigned to @yegor256, can't assign to @yegor256

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@rultor release, tag is `0.9.10`

**Comment by yegor256** [comment]
@rultor release, tag is `0.9.10`

**Comment by yegor256** [comment]
@rultor release, tag is `0.9.10`

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#64](https://github.com/yegor256/zold/issues/64) is now out of scope

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#125](https://github.com/zold-io/zold/issues/125) is still not solved.

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#125](https://github.com/zold-io/zold/issues/125) is solved here.
