### ISSUE TITLE
keep scores on disc and restore on start

### ISSUE THREAD

**Issue by yegor256** [yegor256/zold#77]
Let's save scores to a temporary file and restore them back on `node` restart. Now, on each restart we simply lose everything. Would be better to preserve earlier found scores.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@6a151509-d0d4-40fa-a569-53d8cdf9ca67, thread: pool-789-thread-1
com.amazonaws.http.AmazonHttpClient$RequestExecutor[1113] com.amazonaws.SdkClientException: Unable to execute HTTP request: null
sun.nio.ch.FileChannelImpl[110] java.nio.channels.ClosedChannelException: null
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): Issue: zerocracy/zold#77, Action: `assigned`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@6a151509-d0d4-40fa-a569-53d8cdf9ca67, thread: pool-790-thread-1
com.zerocracy.pm.Claims[113] java.lang.IllegalStateException: Duplicate claims are not allowed in [C91QJT4CF](https://www.0crat.com/p/C91QJT4CF), can't add this XML to 2 existing ones (Add job to WBS;{job=gh:zerocracy/zold#77, reason=GitHub issue was assigned to 0crat, role=DEV},Add job to WBS;{job=gh:zerocracy/zold#77, reason=GitHub issue was assigned to 0crat, role=DEV}):
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1480634635">
   <created>2018-05-28T06:00:38.436Z</created>
   <type>Add job to WBS</type>
   <token>github;zerocracy/zold;77</token>
   <params>
      <param name="job">gh:zerocracy/zold#77</param>
      <param name="role">DEV</param>
      <param name="reason">GitHub issue was assigned to 0crat</param>
   </params>
</claim>

```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): Issue: zerocracy/zold#77, Action: `assigned`

**Comment by 0crat** [comment]
Job [#77](https://github.com/zerocracy/zold/issues/77) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Job [#77](https://github.com/zerocracy/zold/issues/77) is already in scope

**Comment by yegor256** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/zold/issues/77#issuecomment-392445127))

@yegor256 Job [#77](https://github.com/yegor256/zold/issues/77) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#77](https://github.com/yegor256/zold/issues/77); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@rultor release, tag is `0.10.14`

**Comment by 0crat** [comment]
The job [#77](https://github.com/yegor256/zold/issues/77) is now out of scope
