### ISSUE TITLE
validate public key on merge

### ISSUE THREAD

**Issue by yegor256** [yegor256/zold#87]
When we merge, let's make sure the public key matches.

**Comment by 0crat** [comment]
Job [#87](https://github.com/yegor256/zold/issues/87) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#87](https://github.com/yegor256/zold/issues/87); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@24b34ee2-112b-48ac-b25b-4b5b5639b958, thread: pool-320-thread-1
java.lang.Thread[-2] java.lang.OutOfMemoryError: unable to create new native thread
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): Issue: yegor256/zold#87, Action: `closed`
