### ISSUE TITLE
Remote update fails

### ISSUE THREAD

**Issue by biboran** [yegor256/zold#90]
Calling `zold --trace remote update` on a version **0.9.10** produces an unexpected error:
```
ERROR: undefined method `error' for #<Zold::Remote:0x000055be2d494710> (NoMethodError)
/usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/zold-0.9.10/lib/zold/commands/remote.rb:140:in `block in update'
/usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/zold-0.9.10/lib/zold/commands/remote.rb:118:in `each'
/usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/zold-0.9.10/lib/zold/commands/remote.rb:118:in `update'
/usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/zold-0.9.10/lib/zold/commands/remote.rb:80:in `run'
/usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/zold-0.9.10/bin/zold:133:in `<top (required)>'
/usr/local/rbenv/versions/2.5.1/bin/zold:23:in `load'
/usr/local/rbenv/versions/2.5.1/bin/zold:23:in `<main>'
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@biboran[/z](https://www.0crat.com/u/biboran) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C91QJT4CF) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@biboran can you reproduce it with 0.9.11? (just released)

**Comment by biboran** [comment]
@yegor256 no longer reproduces

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
