### ISSUE TITLE
The defence from analogue of the 51% attack will not work.

### ISSUE THREAD

**Issue by vizotov** [yegor256/zold#91]
Quotation from the "White paper": 

"but a fetching node may always re-validate the entire wallet, by checking RSA signatures of all transactions".

This will not save from 51% attack, because the attack will be made for those who want to double spent his money.
Thus, all transactions will be signed properly.

In the Zold the situation with 51% attack is significant worse, than in the Bitcoin.
In the Bitcoin an intruder has to get more than 51% of all calculating resources of the Bitcoin network, because all nodes are calculating ONE blockchain. Their calculation resources are added up.

In Zold one node is calculating itself little blockchain. Thus, the intruder has to use more resources than one node, rather than all nodes. It is the real ability to attack with a powerful server.

1. I create an ordinary transaction, and the network accept it.
2. I take backed up copy of the ledger without this transaction and add the double spending transaction.
3. Then I calculate on it much bigger score with a powerful server and send it to network.
4.  The ledger with the fraudulent transaction replaces in the network the previous one with the correct transaction.
.

**Comment by yegor256** [comment]
@vizotov keep in mind that during MERGE we summarize all scores of all nodes. Thus, your single powerful server will only be able to create a single score. While other nodes will have bigger cumulative score.

**Comment by yegor256** [comment]
@vizotov yes, all nodes will try to keep all wallet files. Of course, not all of them will manage to do that, but they will try to.

**Comment by vizotov** [comment]
@yegor256, OK. This will solve the problem.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
