### ISSUE TITLE
push takes too long on the server

### ISSUE THREAD

**Issue by yegor256** [yegor256/zold#97]
Let's make it async

**Comment by yegor256** [comment]
@rultor release, tag is `0.10.8`

**Comment by yegor256** [comment]
@rultor release, tag is `0.10.8`

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@24b34ee2-112b-48ac-b25b-4b5b5639b958, thread: pool-1743-thread-1
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "roles.xml" in "C91QJT4CF" in 1min: 442e17af4e0c/4hr/0/0/false/false by QuartzScheduler_Worker-3
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): Issue: yegor256/zold#97, Action: `opened`
